### ISSUE TITLE
Navigation Question

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS500#24]
@smecastellon @kenmonroe @Imbenzig 

I had Michelle visit the homepage yesterday and she was confused by the fact that the pages linked from the callouts opened in a new tab.

Do any of you have issue with having those links open in the same tab/window?

**Comment by kenmonroe** [comment]
Opening in a new tab from what I've seen is a fairly standard approach to navigation and presenting information. The advantage is that when the new tab is open a student can toggle between the source and the content which can mean reviewing the context and the information easily. This could be particularly important in referring to the required resources while looking at the learning activities page. Because we haven't link to the required resources - journal articles in the learning activities being able to have both pages open in different tabs makes it easier to get to the information. If new information opens in the same tab, the ability to toggle between is lost and there is only back arrow navigation to the previous page. I think this would quickly become tedious.

It can be a little daunting at first and does need to be presented to students in the orientation of the course and how to navigate in the site. With students properly trained, I think opening in a new tab is a good system.

**Comment by smecastellon** [comment]
We'll have to go over this tomorrow when we meet to post the posts.  Are
you good for f:f at 11:30?


*"Do Justice, love mercy and walk humbly with your God." *Micah 6:8

Adrienne Castellon, EdD

Asst. Prof. and Stream Director of Master's Educational Leadership
Asst. Prof. Master's Special Education
Asst. Prof. Faculty of Education

Trinity Western University
7600 Glover Road
Langley, BC V2Y 1Y1, Canada
email: adrienne.castellon@twu.ca
www.twu.ca/lead
http://www.twu.ca/leadership-ma/education

Current Research:
http://www.teacherresearch.ca/blog/article/2017/05/28/324-a-call-to-personal-research-indigenizing-your-curriculum

[image: cid:34908F1D-3E32-4B46-AD9B-17D22312D87D]

**Comment by cmadland** [comment]
YEs, I’m good for tomorrow. I sent a meeting invite yesterday.

--
COLIN MADLAND, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Jun 21, 2017, at 11:24 AM, smecastellon <notifications@github.com<mailto:notifications@github.com>> wrote:

We'll have to go over this tomorrow when we meet to post the posts. Are
you good for f:f at 11:30?


*"Do Justice, love mercy and walk humbly with your God." *Micah 6:8

Adrienne Castellon, EdD

Asst. Prof. and Stream Director of Master's Educational Leadership
Asst. Prof. Master's Special Education
Asst. Prof. Faculty of Education

Trinity Western University
7600 Glover Road
Langley, BC V2Y 1Y1, Canada
email: adrienne.castellon@twu.ca<mailto:adrienne.castellon@twu.ca>
www.twu.ca/lead<http://www.twu.ca/lead>
http://www.twu.ca/leadership-ma/education

Current Research:
http://www.teacherresearch.ca/blog/article/2017/05/28/324-a-call-to-personal-research-indigenizing-your-curriculum

[image: cid:34908F1D-3E32-4B46-AD9B-17D22312D87D]

**Comment by smecastellon** [comment]
Oh, great - didn't receive a meeting invite.  11:30 tomorrow then!


*"Do Justice, love mercy and walk humbly with your God." *Micah 6:8

Adrienne Castellon, EdD

Asst. Prof. and Stream Director of Master's Educational Leadership
Asst. Prof. Master's Special Education
Asst. Prof. Faculty of Education

Trinity Western University
7600 Glover Road
Langley, BC V2Y 1Y1, Canada
email: adrienne.castellon@twu.ca
www.twu.ca/lead
http://www.twu.ca/leadership-ma/education

Current Research:
http://www.teacherresearch.ca/blog/article/2017/05/28/324-a-call-to-personal-research-indigenizing-your-curriculum

[image: cid:34908F1D-3E32-4B46-AD9B-17D22312D87D]
