### ISSUE TITLE
Optional Assignment due dates

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS500#29]
We currently have published due dates on the assignment pages in gitBook. This will limit the flexibility that we have in deploying the content in multiple contexts.

I suggest that we remove the due dates from the assignment pages and manage that bit in WordPress.

Thoughts?

**Comment by smecastellon** [comment]
Yes that is sensible since we are using an 'assignment bank' and specifics per offering can best be managed in wordpress.  Good thought Colin!

**Comment by kenmonroe** [comment]
Where dates are fixed and would be applied in each course (eg end of week 5) I would suggest leaving them in Gitbook. Where dates may be assigned at the discretion of the instructor, WP would provide this flexibility. I would make a note in Gitbook that states the due date is "Assigned by instructor". As students want to know, what the assignment is and when it is due. 

My bias is always towards fewer moving parts, or adjustments to be made by an instructor prior to session starting because there seems always a lot to do and having just one fall through the cracks can mess things up. Assignment due dates are a big issue for students so it is important that they be published accurately at all times.

**Comment by cmadland** [comment]
That makes sense, Ken.

Where appropriate, I'll add the 'assigned by instructor' notation and keep the dues dates for those assignments with common due dates.
